// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include <QtCore/QString>

#include <vector>

namespace os::ui {

// The licenses the app shows (About -> Licenses): OpenShape's own, those of
// the libraries built into it and of the third-party code inside Qt, with
// their full texts. They live in resources/licenses/ (built into the app as
// ":/openshape/licenses"), generated by scripts/licenses/licenses.py from
// the exact source archives the iOS app is built from (docs/LICENSING.md).
struct LicenseText {
    QString title;
    QString file; // in <dir>/texts/
};

struct LicenseEntry {
    QString id;      // "openshape", "qt", "occt", ... or "qt:<id>" (inside Qt)
    QString name;
    QString group;   // "app", "library" or "qt"
    QString version;
    QString license; // SPDX expression
    QString usedFor;
    QString copyright;
    QString notice;
    QString homepage;
    QString source;  // where its exact source code is
    std::vector<LicenseText> texts;
};

// What a build is made from (core/Version.h), for the LGPL notice.
struct BuildInfo {
    QString version;     // "0.2.0"
    QString buildNumber; // CFBundleVersion; the version itself on the desktop
    QString commit;      // git commit id, or empty
    QString releaseTag;  // "v0.3.0" for a release build, or empty

    static BuildInfo current();
};

inline constexpr const char* kLicensesDir = ":/openshape/licenses";
inline constexpr const char* kRepositoryUrl = "https://github.com/SamuelAirs/openshape";
// Where the written source offer can be claimed (the project's public
// issue tracker; docs/LICENSING.md).
inline constexpr const char* kSourceContactUrl = "https://github.com/SamuelAirs/openshape/issues";

class LicenseCatalog {
public:
    // Reads <dir>/index.json. On failure the catalog is empty and error()
    // says why (a broken build; the tests and the acceptance run catch it).
    static LicenseCatalog load(const QString& dir = QString::fromLatin1(kLicensesDir));

    bool isValid() const { return error_.isEmpty() && !entries_.empty(); }
    const QString& error() const { return error_; }
    const std::vector<LicenseEntry>& entries() const { return entries_; }
    const LicenseEntry* find(const QString& id) const;

    // An entry's page: what it is, its copyright and notice, where its
    // source is, then each license text under its title. Empty for an
    // unknown id or a text that cannot be read.
    QString text(const QString& id) const;

    // The LGPL notice and written source offer (<dir>/source-offer.txt)
    // with the build's version, build, source and library-source links.
    QString sourceOffer(const BuildInfo& build) const;

private:
    QString dir_;
    QString error_;
    std::vector<LicenseEntry> entries_;
};

// The source code of exactly this build: the release tag's tree, else the
// commit's, else the repository.
QString sourceCodeUrl(const BuildInfo& build);
// Where the exact source of the libraries in this build is: the release's
// page with its iOS source archive, else the pins in the source code.
QString librarySourcesText(const BuildInfo& build);
// "build 57, commit 0123456789ab" (what identifies this build), or "a local build".
QString buildDescription(const BuildInfo& build);

} // namespace os::ui
