#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Makes the Windows release files from a packaged folder
# (scripts/package-windows.sh on a release build):
#   <out>/OpenShape-<version>-windows-x64-setup.exe  per-user installer (NSIS)
#   <out>/OpenShape-<version>-windows-x64.zip        the portable folder
#   <out>/SHA256SUMS.txt
# The package must pass the license gate first (scripts/windows/license-gate.sh).
#
# Usage (repository root; MSYS2 ucrt64/bin and usr/bin first in PATH):
#   scripts/windows/make-installer.sh [package-dir] [output-dir]
# Defaults: dist/OpenShape  dist
# Needs: pacman -S mingw-w64-ucrt-x86_64-nsis mingw-w64-ucrt-x86_64-python
# For tests only: OPENSHAPE_TEST_DESKTOP_DIR=<folder> makes the installer
# put its desktop shortcut there instead of on the desktop.
set -euo pipefail

PKG=${1:-dist/OpenShape}
OUT=${2:-dist}
ROOT=$(cd "$(dirname "$0")/../.." && pwd)

command -v makensis >/dev/null || { echo "makensis not found (pacman -S mingw-w64-ucrt-x86_64-nsis)"; exit 1; }
command -v python >/dev/null || { echo "python not found (pacman -S mingw-w64-ucrt-x86_64-python)"; exit 1; }
[ -f "$PKG/OpenShape.exe" ] || { echo "missing $PKG/OpenShape.exe (scripts/package-windows.sh)"; exit 1; }

# The version: CMake's project version, which the executable must carry too
# (a stale package would otherwise be released under a new name).
version=$(sed -n 's/^ *VERSION \([0-9][0-9.]*\)$/\1/p' "$ROOT/CMakeLists.txt" | head -n 1)
[[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "could not read the version from CMakeLists.txt ('$version')"; exit 1; }
exe_version=$(powershell.exe -NoProfile -Command "(Get-Item '$(cygpath -w "$PKG/OpenShape.exe")').VersionInfo.ProductVersion" | tr -d '\r')
[ "$exe_version" = "$version" ] || { echo "$PKG/OpenShape.exe is version '$exe_version', CMakeLists.txt says $version: package again"; exit 1; }

# Only GPL-free packages are distributed. The gate compares the packaged
# OCCT DLLs with OpenShape's OCCT build: $OPENSHAPE_OCCT_PREFIX, by default
# the CMake release preset's.
occt_prefix=${OPENSHAPE_OCCT_PREFIX:-}
if [ -z "$occt_prefix" ]; then
    # The CMake preset's default. MSYS2's bash does not always inherit
    # USERPROFILE (and has its own HOME): ask Windows.
    profile=${USERPROFILE:-$(powershell.exe -NoProfile -Command "[Environment]::GetFolderPath('UserProfile')" | tr -d '\r')}
    occt_prefix="$(cygpath -m "$profile")/opt/occt-7.9.3-openshape"
fi
mkdir -p "$OUT"
PKG=$(cd "$PKG" && pwd) # makensis resolves relative paths from the .nsi's folder
OUT=$(cd "$OUT" && pwd)
echo "License gate with OpenCASCADE from $occt_prefix"
"$ROOT/scripts/windows/license-gate.sh" "$PKG" "$occt_prefix" > "$OUT/license-gate.txt" || {
    cat "$OUT/license-gate.txt"; echo "The package failed the license gate: not making release files."; exit 1; }
tail -n 1 "$OUT/license-gate.txt"

name="OpenShape-$version-windows-x64"
setup="$OUT/$name-setup.exe"
zip="$OUT/$name.zip"
work="$OUT/.installer"
rm -rf "$work"
mkdir -p "$work"

# The uninstaller removes exactly the packaged files, then the folders if
# they are empty (deepest first), so it never deletes anything else.
{
    echo "; Generated by scripts/windows/make-installer.sh from $PKG: do not edit."
    echo "!macro OPENSHAPE_UNINSTALL_FILES"
    (cd "$PKG" && find . -type f | sed 's|^\./||' | sort) | while read -r file; do
        case "$file" in *'$'*|*'"'*|*'`'*) echo "unsupported character in $file" >&2; exit 1 ;; esac
        echo "  Delete \"\$INSTDIR\\${file//\//\\}\""
    done
    (cd "$PKG" && find . -mindepth 1 -type d | sed 's|^\./||' | sort -r) | while read -r dir; do
        echo "  RMDir \"\$INSTDIR\\${dir//\//\\}\""
    done
    echo "!macroend"
} > "$work/files.nsh"

# The license page shows the MPL text; NSIS wants CRLF line breaks.
sed 's/\r$//; s/$/\r/' "$ROOT/LICENSE" > "$work/LICENSE.txt"

size_kb=$(du -sk "$PKG" | cut -f1)
file_count=$(find "$PKG" -type f | wc -l)
defines=(
    "-DVERSION=$version"
    "-DSOURCE_DIR=$(cygpath -w "$PKG")"
    "-DFILES_NSH=$(cygpath -w "$work/files.nsh")"
    "-DSIZE_KB=$size_kb"
    "-DICON_FILE=$(cygpath -w "$ROOT/resources/icons/openshape.ico")"
    "-DLICENSE_FILE=$(cygpath -w "$work/LICENSE.txt")"
    "-DOUTFILE=$(cygpath -w "$setup")"
)
if [ -n "${OPENSHAPE_TEST_DESKTOP_DIR:-}" ]; then
    mkdir -p "$OPENSHAPE_TEST_DESKTOP_DIR"
    defines+=("-DTEST_DESKTOP_DIR=$(cygpath -w "$(cd "$OPENSHAPE_TEST_DESKTOP_DIR" && pwd)")")
    echo "TEST BUILD: desktop shortcut goes to $OPENSHAPE_TEST_DESKTOP_DIR"
fi
rm -f "$setup"
# makensis needs a writable TEMP (a shell started from another shell may
# not pass it on; then it tries C:\Windows).
TMP=$(cygpath -w "$work") TEMP=$(cygpath -w "$work") MSYS2_ARG_CONV_EXCL='*' makensis -V2 -INPUTCHARSET UTF8 "${defines[@]}" "$(cygpath -w "$ROOT/packaging/windows/openshape.nsi")"

# The portable zip: the folder as OpenShape-<version>/ (Python's zipfile:
# no extra tools, same on every machine).
rm -f "$zip"
python - "$(cygpath -w "$PKG")" "$(cygpath -w "$zip")" "OpenShape-$version" <<'PY'
import os, sys, zipfile
src, dst, top = sys.argv[1:4]
with zipfile.ZipFile(dst, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for folder, dirs, files in os.walk(src):
        dirs.sort()
        for name in sorted(files):
            path = os.path.join(folder, name)
            z.write(path, os.path.join(top, os.path.relpath(path, src)).replace(os.sep, "/"))
PY

(cd "$OUT" && sha256sum "$(basename "$setup")" "$(basename "$zip")" > SHA256SUMS.txt)
rm -rf "$work"

setup_size=$(du -h "$setup" | cut -f1)
zip_size=$(du -h "$zip" | cut -f1)
echo "Installer: $setup ($setup_size)"
echo "Zip:       $zip ($zip_size)"
echo "Package:   $file_count files, $((size_kb / 1024)) MiB installed"
cat "$OUT/SHA256SUMS.txt"
