# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Writes core/SourceCommit.h: the git commit a build is made from, for the
# LGPL's relinking notice in About -> Licenses (docs/LICENSING.md). Runs on
# every build (the openshape_source_commit target in src/core/CMakeLists.txt),
# not only when CMake configures, so a new commit never leaves an older id in
# the app. The file is rewritten only when its text changes, so only the code
# that includes it recompiles, and only then.
#
#   cmake -DOUTPUT=<file> -DSOURCE_DIR=<checkout> [-DCOMMIT=<id>]
#         [-DGIT_EXECUTABLE=<git>] -P SourceCommit.cmake
#
# COMMIT given (release and CI builds: scripts/ios/build-app.sh): that id.
# Otherwise git's HEAD, but only when no tracked file differs from it: a
# build with local changes is not that commit's code, so it names none
# ("a local build").

if(NOT OUTPUT OR NOT SOURCE_DIR)
    message(FATAL_ERROR "SourceCommit.cmake needs -DOUTPUT and -DSOURCE_DIR")
endif()

set(commit "${COMMIT}")
set(how "given")
if(commit STREQUAL "")
    set(how "unknown")
    if(GIT_EXECUTABLE)
        execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE head OUTPUT_STRIP_TRAILING_WHITESPACE
            RESULT_VARIABLE head_result ERROR_QUIET)
        if(head_result EQUAL 0 AND head MATCHES "^[0-9a-f]+$")
            execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
                WORKING_DIRECTORY "${SOURCE_DIR}"
                OUTPUT_VARIABLE changes OUTPUT_STRIP_TRAILING_WHITESPACE
                RESULT_VARIABLE status_result ERROR_QUIET)
            if(status_result EQUAL 0 AND changes STREQUAL "")
                set(commit "${head}")
                set(how "git HEAD, no local changes")
            elseif(status_result EQUAL 0)
                set(how "git HEAD with local changes: none named")
            endif()
        endif()
    endif()
endif()
if(NOT commit MATCHES "^[0-9a-f]*$")
    message(FATAL_ERROR "OPENSHAPE_SOURCE_COMMIT must be a git commit id (hex), not '${commit}'")
endif()

string(CONCAT text
    "// Generated by src/core/SourceCommit.cmake on every build: do not edit.\n"
    "// (${how})\n"
    "\n"
    "#pragma once\n"
    "\n"
    "namespace os {\n"
    "\n"
    "// The git commit this build is made from (About -> Licenses); empty when\n"
    "// unknown or when the build has changes that are not committed.\n"
    "inline constexpr const char* kSourceCommit = \"${commit}\";\n"
    "\n"
    "} // namespace os\n")

set(old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" old)
endif()
if(NOT old STREQUAL text)
    file(WRITE "${OUTPUT}" "${text}")
endif()
